### ISSUE TITLE
createRehydrateReducer parameters types incompatible

### ISSUE THREAD

**Issue by AdamKappa** [amdor/ngrx-rehydrate#1]
I just change my "classic" reducer (from createReducer) to use your createRehydrateReducer by adding the { key:"key1"} and I get this error 

> Argument of type 'ReducerTypes<favoritePhotoState, [ActionCreator<"Add photo to Favorites", (props: { photoID: number; }) => { photoID: number; } & TypedAction<"Add photo to Favorites">>]>' is not assignable to parameter of type 'ReducerTypes<favoritePhotoState, ActionCreator[]>'.
> 
>     Types of property 'reducer' are incompatible.
> 
>         Type 'OnReducer<favoritePhotoState, [ActionCreator<"Add photo to Favorites", (props: { photoID: number; }) => { photoID: number; } & TypedAction<"Add photo to Favorites">>], favoritePhotoState, favoritePhotoState>' is not assignable to type 'OnReducer<favoritePhotoState, ActionCreator[]>'.
> 
>     Types of parameters 'action' and 'action' are incompatible.
> 
>         Type 'object & { type: string; }' is not assignable to type '{ photoID: number; } & TypedAction<"Add photo to Favorites"> & { type: "Add photo to Favorites"; }'.
> 
>         Property 'photoID' is missing in type '{ type: string; }' but required in type '{ photoID: number; }'.
> 
> 

[Here you can find](https://stackoverflow.com/questions/78589598/how-to-rehydrate-my-store-using-createrehydratereducer-from-package-ngrx-rehyd) details about the issue + the code

**Comment by AK47-AK47** [comment]
Thanks for your efforts!
As I don't want to stay to Angular v17, I decide to use(copy/paste and modify as needed) your function locally in my project and not import it as dependency.
[Here](https://stackblitz.com/edit/nativescript-stackblitz-templates-fvy2zi?file=create-rehydrate-reducer.ts) is how I implement your function locally and use it in my project as shared via 

`import { createRehydrateReducer } from "../shared/create-rehydrate-reducer";`

 

Thanks again!!
